name: p15_bildergalerie
description: "Eine persönliches Galerie-Projekt in Fluttetr."
publish_to: 'none'
version: 0.1.0

platforms:
  android:
  ios:

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/